[build]
  command = "cd ../.. && npm install && npm run build && cp -r node_modules/remix-routes/node_modules/.remix-routes node_modules/remix-routes && cp -r node_modules/remix-routes/node_modules/.remix-routes node_modules/ && cp -r node_modules/remix-routes/node_modules/.remix-routes apps/web/public/build"
  publish = "public/build"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
